language: node_js
sudo: false
node_js:
- '5'
addons:
  code_climate:
    repo_token: d2836b4e4843c0c4d3bbc4cb21143bce108cfe5b5592660a7da2aac32ad6e698
env:
  global:
  - AWS_ACCESS_KEY_ID=AKIAJH2D5IPIRHYJT5IA
  - secure: Bwmu/JXz7iT+k9/bNVJx2Y4oSkG6qhY+ogpAxiJl1fOsfGpZTWt3nlwerN90IaZgxk+HF91QcI/L+QzyJIPWrZjTaI1ndmzPuefj5gI/CwRH8lqwhxg+3WrYkOPtxSVTG4pmmuyIYxMERg0s5zTQTimm6WcJi4JrBSIfn5Gk/vf1yw8ZjxGuzthef8pfEO5Y4JUzqCBdheS4H1fsRapbMI4O6HD9j+ysw96kvXPu/q6cEb0UHGV1Qr3Jb6p7KwIy4x1bnh2haups8cDPPNagzWr3IfDVhfga1Avn4PXx+jOSsB7T3jlioWA4en+LFARexh4ZhMo+F+841WKgp/B3QvAzQfnXSBmxwdqgaF3LBRkJdlRHgN8kloNnOIbbfZdy0TIhIqjO4jftQQ72oHJW4lcFggHnMvzjnQcZ2wei5llOywcZCkusc0pjEUs7HnQxLDIemmLkZdVx4rc0OK1M+leoHJLi0A2wGxgi5kr2xvj1uJprJsUwOty64J7yf/jDjUsIZeyXHZdYAJBTBtmoOHJCi3gLFesI6Jx6z2XOBstEytaeydOiSc08tE3IEVcv0AAwHceHS+jdpEI+CGgHs1/81XiFUj91NiUHU3ye7zhRr83WkMEZcmgGgY6k/JnePZ9yekYPrcV3iMEoD7cbVjFQ0fNHH+ZkzLsgE9iyiQU=
before_script:
- npm install -g codeclimate-test-reporter
- if [ ${TRAVIS_BRANCH} == master ]; then export NODE_ENV=production; else export NODE_ENV=staging; fi
after_script:
- codeclimate-test-reporter < coverage/lcov.info
after_success:
- npm install --global webpack
- NODE_ENV=production webpack --config webpack.config.prod.js
- mkdir build
- cp -r index.html dist build/
- for file in `find build -type f`; do gzip --best $file && mv $file.gz $file; done
# after_deploy:
# - "./deploy/invalidate-cloudfront.sh $AWS_ACCESS_KEY_ID $AWS_SECRET_ACCESS_KEY $TRAVIS_BRANCH"
deploy:
  provider: s3
  access_key_id: AKIAJH2D5IPIRHYJT5IA
  secret_access_key:
    secure: "YaaiOVfxXFIGChuuNwqODft8MvUrkfMySLp0wYaNbdaNl4ePrJXoBg+8VPheRcqs6nCPKJ6mA/dUWF1D8WxwRsSSzzcuhTXeVKZph/HIDAp90JxA32UQi0tK9wSZOQ4hnq+zEyNgC0Bw7sQizixtEosozZmK5yZaRMMjLqFTCA+x6QLYmGgcai/lQ4z+pS6IKzM3VNUvOFeqBwFuvzDrBxcmP5r+6DZvtts6104nkPb5oXc6tWQ6yLnhD9TAzC2Kw8EUDOVAd7XOvgpB/zEFx2o7q8gL7Gt5HcRHa7OR0NFofXFhjbRyclAWT4hcQUv1wyjm7LiGePL/rVDHD1lspTFRmz9BmBPedmOcrHvqMCKQEyKCTPnBRSSHzHEKkiGfFmgCczdTLE1zUhs6m3yxwWwB4UzT8aIU0OnZ1CVgaT4UIZfY+1b6pIAktYi2OPLSldzYBjzesAVhGrsMvcr4tXXGFIvw0YfsxSCzHqerkcrbS07nS7lZvP+fWPelOmub/BeLBoD3AAb0OO6RRMClAquEEII6iKXMn2UWhl2qSAAzUN3s1SQKN6+PXcGDibzbeE22pf03X/bYmdkJS8G7xlDsrDUq+MhYgxGRWeXuYUA6/u+3u6XBFbB6gJFiFmeNFFf16I8gm/AT2z+E/DrxhAniVNfK0TJtqAZLXTJGTC8="
  bucket: gateblu.octoblu.com
  local_dir: build
  skip_cleanup: true
  endpoint: gateblu.octoblu.com.s3-website-us-west-2.amazonaws.com
  detect_encoding: true
  region: us-west-2
  on:
    tags: true
